export enum IMC {
  UNDERWEIGHT = 'UNDERWEIGHT',
  NORMAL = 'NORMAL',
  OVERWEIGHT = 'OVERWEIGHT',
  OVERWEIGHT_LEVEL_1 = 'OVERWEIGHT_LEVEL_1',
  OVERWEIGHT_LEVEL_2 = 'OVERWEIGHT_LEVEL_2',
  OBESE = 'OBESE',
  NOT_DEFINED = 'NOT DEFINED'
}
